// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shyumrdufygqcmkjtggy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeXVtcmR1ZnlncWNta2p0Z2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mzk0MjUsImV4cCI6MjA2OTUxNTQyNX0.19DzNxo5f2r7gEQTc5bCOia0xOGc-8zosXcFMJcpnwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});